# FROM node:16-bullseye
# EXPOSE 8000

# RUN npm install -g gatsby-cli
# WORKDIR /app
# COPY ./package.json /app
# RUN npm cache clean --force
# RUN npm install --legacy-peer-deps
# COPY . /app

# CMD ["gatsby", "develop", "-H", "0.0.0.0" ]

FROM node:14-alpine
EXPOSE 8000
RUN npm install -g gatsby-cli
WORKDIR /app
COPY ./package.json /app
RUN npm cache clean --force
RUN npm install
COPY . /app
CMD ["gatsby", "develop", "-H", "0.0.0.0" ]